### ISSUE TITLE
PROD: Problem loading a session file

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#795]
The session file was created in PROD. When I try to open it, I cannot see the nodes. See image below. Also pasted here is the text from console log. Note that when I was trying to change node shapes using Shape By, it was not doing anything. But now that I saved the session and re-opened, I can see that the node shape key table is open, meaning that it did something on the back end. I emailed you the session file with this Issue number in the subject line.

Uncaught Error: Syntax error, unrecognized expression: #(Unknown)
    at se.error (bundle.primary.js:2:13606)
    at se.tokenize (bundle.primary.js:2:21617)
    at se.select (bundle.primary.js:2:22444)
    at Function.se [as find] (bundle.primary.js:2:7089)
    at S.fn.init.find (bundle.primary.js:2:25014)
    at <anonymous>:1390:10
    at Array.forEach (<anonymous>)
    at HTMLSelectElement.<anonymous> (<anonymous>:1351:14)
    at HTMLSelectElement.dispatch (bundle.primary.js:2:43090)
    at v.handle (bundle.primary.js:2:41074)

<img width="1666" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBenNjQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1de170904da60f3383c9821e4d3f5682c767d7b7/image.png" alt="image.png" />

**Comment by dacowan404** [comment]
Prod version doesn't like using the value (Unknown) to shape by when I switched to the value Unknown it worked. Also it didn't like 1a/3a or 1a/3a/4a for HCV genotype but 1a3a and 1a3a4a worked.  The Angular version doesn't have this problem.
Also for HCV, it was creating different shapes for Nonreactive, non-reactive, and Non-Reactive so I updated those values to be Non-Reactive.
I'll send you the updated MicrobeTrace file.

**Comment by ikb6** [comment]
Still seeing this issue for a different session file. The file can be found here. No nodes seen. when it loads, then when I go in and set Node Shape by to none (it was set to co-infection), then the nodes appear. 

https://cdc.sharepoint.com/:u:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/Issue_812_HCV_WI_Jie_Anupama.microbetrace?csf=1&web=1&e=apsqGo

**Comment by ikb6** [comment]
@dacowan404

**Comment by ikb6** [comment]
Node key tables are not showing when session is loaded
